<?php

return [
    'root' => 'instrumente-si-mobilier',

    'main_sections' => [
        'echipamente-pentru-service',
        'mobilier-pentru-service',
        'scule-speciale-auto',
        'instrument-manual',
        'scule-pneumatice',
        'electroinstrumente',
        'instrumente-electromontaj',
        'instrumente-de-masurare',
        'accesorii-si-consumabile',
        'sudura-richtuire-vopsire',
        'vulcanizare',
        'echipament-protectie',
    ],

    'parent_overrides' => [
        'echipamente-pentru-service' => 'instrumente-si-mobilier',
        'sudura-richtuire-vopsire' => 'instrumente-si-mobilier',
        'vulcanizare' => 'instrumente-si-mobilier',
        'echipament-protectie' => 'instrumente-si-mobilier',
        'carucioare-pentru-rafturi' => 'mobilier-pentru-service',
        'carucioare-de-scule' => 'mobilier-pentru-service',
        'accesorii-pentru-bancuri-de-lucru' => 'mobilier-pentru-service',
        'seringi-si-palnii' => 'echipamente-schimb-ulei',
        'suflante-de-ulei-solide' => 'echipamente-schimb-ulei',
        'hidrometre-si-refractometre' => 'instrumente-control-verificare',
        'remediu' => 'echipament-protectie',
        'goniometre' => 'instrumente-de-masurare',
        'chei-cu-acumulator' => 'electroinstrumente',
        'baterii-incarcatoare' => 'electroinstrumente',
        'pistoale-impact-cu-acumulator' => 'electroinstrumente',
        'instrumente-izolate-vde' => 'instrumente-electromontaj',
        'scule-transmisie-ambreiaj' => 'scule-speciale-auto',
        'scule-aer-conditionat-auto' => 'scule-speciale-auto',
        'scule-sistem-racire-auto' => 'scule-speciale-auto',
        'menghine-si-cleme' => 'instrument-manual',
        'ciocane-si-unelte-lovire' => 'instrument-manual',
        'nituitoare-manuale' => 'instrument-manual',
    ],

    'aliases' => [
        'pistoale-pneumatice-si-impact' => 'chei-pneumatice',
        'extractoare-si-scule-speciale' => 'extractoare-si-prese',
        'grup-motor' => 'scule-pentru-motor',
        'unelte-speciale-pentru-camioane' => 'scule-vehicule-grele',
        'inserturi-biti-cu-tija-de-14' => 'biti-insertii-adaptoare',
        'soclu-si-insertii-de-capat-biti' => 'biti-insertii-adaptoare',
        'seturi-de-biti-si-accesorii' => 'biti-si-capete',
        'seturi-de-scule-universale' => 'seturi-de-scule',
        'instrument-inch' => 'tubulare-si-clichete',
        'burghie-pentru-metal' => 'burghie-freze',
        'instrumente-pentru-reparatii-si-curatare' => 'accesorii-universale',
        'instrumente-cu-acumulator' => 'electroinstrumente',
        'pistoale-impact-cu-acumulator' => 'chei-cu-acumulator',
    ],

    'non_assignable' => [
        'instrumente-si-mobilier',
        'remediu',
        'pistoale-pneumatice-si-impact',
        'extractoare-si-scule-speciale',
        'grup-motor',
        'unelte-speciale-pentru-camioane',
        'inserturi-biti-cu-tija-de-14',
        'soclu-si-insertii-de-capat-biti',
        'seturi-de-biti-si-accesorii',
        'seturi-de-scule-universale',
        'instrument-inch',
        'burghie-pentru-metal',
        'instrumente-pentru-reparatii-si-curatare',
    ],

    'sku_prefixes' => [
        'NC-' => 'chei-pneumatice',
        'RA-' => 'surubelnite-pneumatice',
        'QE-' => 'burghie-pneumatice',
        'DW-' => 'chei-cu-acumulator',
        'DS-' => 'chei-cu-acumulator',
        'DB-' => 'baterii-incarcatoare',
        'DC-' => 'baterii-incarcatoare',
    ],

    'sku_overrides' => [
        'JTC-4464' => 'scule-pentru-motor',
        'JTC-4476' => 'scule-pentru-motor',
        'JTC-4171' => 'scule-pentru-motor',
        'JTC-4351' => 'scule-pentru-motor',
        'JTC-6621' => 'scule-pentru-motor',
        'JTC-4577' => 'scule-pentru-motor',
        'JTC-4509' => 'scule-pentru-motor',
        'JTC-4084' => 'scule-pentru-motor',
        'JTC-4767' => 'scule-pentru-motor',
        'JTC-4850' => 'scule-pentru-motor',
        'JTC-6844' => 'scule-pentru-motor',
        'JTC-6628' => 'scule-pentru-motor',
        'JTC-4054' => 'scule-pentru-motor',
        'JTC-4435' => 'scule-pentru-motor',
        'JTC-5467' => 'scule-pentru-motor',
        'JTC-4145' => 'scule-pentru-motor',
        'JTC-4181' => 'scule-pentru-motor',
        'JTC-4338' => 'scule-pentru-frane',
        'JTC-4729' => 'scule-aer-conditionat-auto',
        'JTC-4822' => 'scule-sistem-racire-auto',
        'JW0832' => 'scule-pentru-motor',
        'JTC-4566' => 'scule-speciale-auto',
        'JTC-7984' => 'scule-speciale-auto',
        'JTC-2120' => 'scule-speciale-auto',
        'JTC-6927' => 'scule-speciale-auto',
        'SJ-BNF1664' => 'nituitoare-capsatoare-si-cuie-pneumatice',
        'SJ-TN64' => 'nituitoare-capsatoare-si-cuie-pneumatice',
        'JTC-1412' => 'scule-pentru-suspensie',
        'JTC-1410' => 'scule-pentru-suspensie',
        'HT7G139' => 'seturi-scule-electrice-izolate',
        'HT8G401' => 'extractoare-si-prese',
        'HT8G404' => 'extractoare-si-prese',
        'HT1P186' => 'clesti-electrician-si-cabluri',
        '9CK-101' => 'ochelari-protectie-fata',
        '9CK-102' => 'ochelari-protectie-fata',
        '9TP12' => 'accesorii-protectie',
        '9TP11' => 'accesorii-protectie',
        '9TP22' => 'accesorii-protectie',
        '9TH31-2L' => 'manusi',
        '9TH31-XL' => 'manusi',
        '9TH41-L' => 'manusi',
        '9TH41-XL' => 'manusi',
        '9TH45-XXL' => 'manusi',
        '9TH45-XL' => 'manusi',
        '9TH43-XL' => 'manusi',
        '9TH43-XXL' => 'manusi',
        '9TH42-XL' => 'manusi',
        '9TH42-XXL' => 'manusi',
        '9TH44-XL' => 'manusi',
        '9TH44-XXL' => 'manusi',
        '9TH21XL' => 'manusi',
    ],

    'rules' => [
        'chei-pneumatice' => ['пневмогайковерт', 'пневмогайковёрт', 'гайковерт пневматический', 'гайковёрт пневматический', 'air impact wrench'],
        'clichete-pneumatice' => ['пневмотрещотка', 'пневматическая трещотка', 'air ratchet'],
        'ciocane-pneumatice' => ['пневмомолоток', 'молоток пневматический', 'air hammer'],
        'burghie-pneumatice' => ['пневмодрель', 'дрель пневматическая', 'air drill'],
        'surubelnite-pneumatice' => ['пневмоотвертка', 'пневмоотвёртка', 'отвертка пневматическая', 'air screwdriver'],
        'polizoare-si-slefuitoare-pneumatice' => ['пневмошлифмашина', 'пневматическая шлифовальная машина', 'шлифмашинка пневматическая', 'пневматическая полировальная машина', 'турбинка', 'air grinder', 'air sander'],
        'foarfeci-ferastraie-si-debitare-pneumatice' => ['пневмопила', 'пневмоножовка', 'ножницы пневматические', 'пневматическая отрезная машина', 'air saw'],
        'nituitoare-capsatoare-si-cuie-pneumatice' => ['пневмозаклепочник', 'пневмозаклёпочник', 'пневматический заклепочник', 'air riveter'],
        'pistoale-suflat-si-sablare' => ['пистолет продувочный', 'пистолет моечный', 'пистолет пескоструйный', 'пистолет подкачки шин', 'пенообразователь', 'tornador', 'blow gun', 'sandblasting gun'],
        'pistoale-pentru-silicon-si-gresare' => ['пневматический шприц', 'шприц для смазки', 'пистолет для смазки', 'пистолет для силикона', 'grease gun', 'silicone gun'],
        'furtunuri-cuple-accesorii' => ['пневмошланг', 'воздушный шланг', 'быстросъемная муфта', 'быстросъёмная муфта', 'смазочная муфта', 'фитинг пневматический', 'air hose', 'air coupler'],
        'consumabile-pentru-scule-pneumatice' => ['точильный камень', 'зачистной диск', 'лента абразивная', 'сменная подошва', 'иглы для пневмомолотка'],
        'compresoare' => ['воздушный компрессор', 'компрессор поршневой', 'air compressor'],
        'chei-dinamometrice' => ['динамометрический ключ', 'torque wrench', 'cheie dinamometrica'],
        'capete-tubulare-impact' => ['ударная головка', 'головка ударная', 'impact socket', 'cr mo socket'],
        'tubulare-si-clichete' => ['торцевая головка', 'головка свечная', 'трещотка ручная', 'вороток', 'удлинитель для головок', 'socket set', 'ratchet handle'],
        'surubelnite-si-biti' => ['отвертка крестовая', 'отвёртка крестовая', 'отвертка шлицевая', 'набор отверток', 'screwdriver'],
        'biti-insertii-adaptoare' => ['бита torx', 'бита hex', 'держатель бит', 'адаптер для головок', 'переходник для головок', 'bit holder'],
        'chei-si-surubelnite' => ['ключ комбинированный', 'ключ рожковый', 'ключ накидной', 'гаечный ключ', 'combination wrench', 'spanner'],
        'clesti-si-instrumente-taiere' => ['плоскогубцы', 'пассатижи', 'бокорезы', 'кусачки', 'зажим ручной', 'pliers', 'side cutter'],
        'tarozi-filiere-filetare' => ['метчик', 'плашка', 'восстановление резьбы', 'thread repair', 'tap and die'],
        'taiere-pilire-prelucrare' => ['напильник', 'ножовка ручная', 'зубило ручное', 'ручная пила', 'file set'],
        'seturi-de-scule' => ['набор инструментов', 'комплект инструментов', 'инструменты в ложементе', 'tool set', 'trusa de scule'],
        'baterii-incarcatoare' => ['аккумулятор lihd', 'аккумулятор li ion', 'зарядное устройство для аккумулятора', 'battery pack', 'battery charger'],
        'chei-cu-acumulator' => ['аккумуляторный гайковерт', 'аккумуляторный ударный ключ', 'cordless impact wrench'],
        'masini-gaurit-insurubat' => ['электрическая дрель', 'сетевая дрель', 'шуруповерт электрический', 'аккумуляторная дрель', 'дрель шуруповерт', 'дрель-шуруповерт', 'corded drill', 'cordless drill'],
        'polizoare' => ['угловая шлифовальная машина электрическая', 'болгарка электрическая', 'электрическая шлифмашина', 'аккумуляторная болгарка', 'corded grinder', 'cordless grinder'],
        'accesorii-scule-electrice' => ['оснастка для электроинструмента', 'принадлежности для электроинструмента'],
        'scule-pentru-filtre-ulei' => ['съемник масляного фильтра', 'съёмник масляного фильтра', 'ключ масляного фильтра', 'oil filter wrench'],
        'scule-pentru-frane' => ['тормозной суппорт', 'тормозной цилиндр', 'прокачка тормозов', 'тормозные колодки инструмент', 'brake tool'],
        'scule-pentru-suspensie' => ['съемник пружин', 'съёмник пружин', 'амортизатор', 'шаровая опора', 'подвеска автомобиля', 'suspension tool'],
        'scule-pentru-motor' => ['фиксация распредвала', 'фиксация коленвала', 'установка грм', 'двигатель инструмент', 'engine timing tool'],
        'extractoare-si-prese' => ['съемник подшипника', 'съёмник подшипника', 'гидравлический съемник', 'гидравлический съёмник', 'извлечения поврежденных болтов', 'поврежденных болтов и гаек', 'экстрактор болтов', 'broken bolt extractor', 'bearing puller'],
        'scule-pentru-roti-vulcanizare' => ['ремонт шин', 'вентиль шин', 'шиномонтажный инструмент', 'колесные болты', 'tire repair tool'],
        'scule-vehicule-grele' => ['инструмент для грузовиков', 'грузовой автомобиль', 'ступичная гайка грузовика', 'truck tool'],
        'diagnoza-auto' => ['автосканер', 'диагностический сканер', 'obd', 'automotive diagnostic'],
        'prese-hidraulice' => ['гидравлический пресс', 'hydraulic press'],
        'cricuri-hidraulice' => ['гидравлический домкрат', 'подкатной домкрат', 'бутылочный домкрат', 'hydraulic jack'],
        'capre-auto-si-suporturi' => ['подставка под автомобиль', 'страховочная стойка', 'jack stand'],
        'pompe-si-cilindri-hidraulici' => ['гидравлический насос', 'гидравлический цилиндр', 'hydraulic pump', 'hydraulic cylinder'],
        'macarale-standuri-suporti-motor' => ['кран для двигателя', 'стойка для двигателя', 'engine crane', 'engine stand'],
        'echipamente-schimb-ulei' => ['замена масла', 'маслосборник', 'откачка масла', 'масленка', 'oil drain', 'oil dispenser'],
        'echipamente-spalare-piese' => ['мойка деталей', 'parts washer'],
        'dulapuri-si-organizare' => ['инструментальный шкаф', 'шкаф для инструментов', 'органайзер для инструментов', 'tool cabinet'],
        'carucioare-de-scule' => ['инструментальная тележка', 'тележка для инструментов', 'tool trolley', 'tool cart'],
        'carucioare-pentru-rafturi' => ['тележка с полками', 'сервисная тележка с полками', 'shelf trolley'],
        'accesorii-pentru-bancuri-de-lucru' => ['аксессуар для верстака', 'принадлежность для верстака', 'workbench accessory'],
        'clesti-electrician-si-cabluri' => ['кабелерез', 'каблерез', 'стриппер', 'обжимные клещи', 'кримпер', 'бокорезы диэлектрические', 'пассатижи для зачистки изоляции', 'плоскогубцы комбинированные диэлектрические', 'плоскогубцы тонконосые прямые диэлектрические', 'cable cutter', 'wire stripper', 'crimping pliers'],
        'testere-electrice-si-indicatoare' => ['индикатор напряжения', 'тестер напряжения', 'бесконтактный детектор напряжения', 'voltage tester'],
        'lipire-si-consumabile' => ['паяльник', 'припой', 'паяльная станция', 'soldering iron'],
        'sublere-micrometre-comparatoare' => ['штангенциркуль', 'микрометр', 'индикатор часового типа', 'caliper', 'micrometer'],
        'multimetre-testere' => ['мультиметр', 'электрический тестер', 'multimeter'],
        'rulete-nivele' => ['рулетка измерительная', 'лазерный уровень', 'строительный уровень', 'измерительная лента', 'spirit level', 'tape measure'],
        'instrumente-control-verificare' => ['рефрактометр', 'ареометр', 'гидрометр', 'манометр', 'измерительный щуп', 'refractometer', 'hydrometer'],
        'discuri-perii-abrazive' => ['абразивный диск', 'отрезной диск', 'шлифовальный круг', 'проволочная щетка', 'abrasive disc'],
        'burghie-freze' => ['сверло по металлу', 'сверло по дереву', 'набор сверл', 'фреза по металлу', 'drill bit'],
        'biti-si-capete' => ['набор бит', 'набор насадок', 'bit set'],
        'cutite-lame-rezerve' => ['сменное лезвие', 'нож технический', 'набор лезвий', 'utility knife', 'replacement blade'],
        'tinichigerie-si-richtuire' => ['рихтовка кузова', 'кузовной ремонт', 'удаление вмятин', 'spotter', 'body repair'],
        'manusi' => ['рабочие перчатки', 'защитные перчатки', 'work gloves'],
        'ochelari-protectie-fata' => ['защитные очки', 'защитная маска', 'защита лица', 'safety goggles', 'face shield'],
        'imbracaminte-lucru' => ['рабочая одежда', 'рабочий комбинезон', 'workwear'],
        'accesorii-protectie' => ['защитная накидка', 'защита крыла автомобиля', 'protective cover'],
    ],

    'compound_rules' => [
        // Broad automotive imports: prefer the vehicle system over a generic puller/tool label.
        ['slug' => 'scule-pentru-filtre-ulei', 'from' => ['scule-speciale-auto', 'instrument-manual'], 'all' => ['фильтр'], 'any' => ['маслян', 'масля'], 'score' => 440, 'evidence' => 'oil-filter terminology'],
        ['slug' => 'scule-pentru-frane', 'from' => ['scule-speciale-auto', 'instrument-manual'], 'any' => ['тормозн', 'суппорт'], 'score' => 430, 'evidence' => 'brake-system terminology'],
        ['slug' => 'scule-pentru-suspensie', 'from' => ['scule-speciale-auto', 'instrument-manual'], 'any' => ['сайлентблок', 'шаровая опор', 'шаровых опор', 'рулев', 'амортиз', 'подвеск', 'ступиц', 'пружин', 'шрус'], 'score' => 425, 'evidence' => 'suspension and steering terminology'],
        ['slug' => 'scule-pentru-motor', 'from' => ['scule-speciale-auto', 'instrument-manual'], 'any' => ['распредвал', 'коленвал', 'коленчат', 'грм', 'форсунк', 'инжектор', 'тнвд', 'свеч', 'клапан', 'поршн', 'двигател', 'компрессометр', 'топливн'], 'score' => 420, 'evidence' => 'engine-system terminology'],
        ['slug' => 'scule-pentru-roti-vulcanizare', 'from' => ['scule-speciale-auto', 'instrument-manual'], 'any' => ['шиномонтаж', 'ремонт шин', 'давления в шинах', 'вентил шин', 'колесн', 'колёсн'], 'score' => 270, 'evidence' => 'wheel and tyre terminology'],
        ['slug' => 'scule-vehicule-grele', 'from' => ['scule-speciale-auto', 'instrument-manual'], 'any' => ['грузовик', 'грузового транспорта', 'truck tool'], 'score' => 270, 'evidence' => 'heavy-vehicle terminology'],
        ['slug' => 'diagnoza-auto', 'from' => ['scule-speciale-auto', 'instrument-manual'], 'any' => ['автосканер', 'диагностический сканер', 'obd'], 'score' => 270, 'evidence' => 'automotive diagnostic terminology'],
        ['slug' => 'extractoare-si-prese', 'from' => ['scule-speciale-auto', 'instrument-manual'], 'any' => ['съемник', 'съёмник', 'экстрактор', 'обратный молоток'], 'score' => 175, 'evidence' => 'generic puller terminology'],
        ['slug' => 'scule-pentru-motor', 'from' => ['scule-speciale-auto'], 'any' => ['распределительн вал', 'водяного насоса', 'шкив генератора', 'датчик кислорода', 'датчиков кислорода', 'форкамер', 'набор фиксаторов', 'фиксатор маховика', 'натяжения ремня', 'поликлинового ремня'], 'score' => 415, 'evidence' => 'specific engine service terminology'],
        ['slug' => 'scule-pentru-suspensie', 'from' => ['scule-speciale-auto'], 'any' => ['ступич', 'ключ для стоек', 'сервисный ключ для стоек'], 'score' => 415, 'evidence' => 'hub or strut service terminology'],
        ['slug' => 'diagnoza-auto', 'from' => ['scule-speciale-auto'], 'any' => ['дымогенератор', 'обнаружения утечек с помощью дыма'], 'score' => 380, 'evidence' => 'automotive leak diagnostic terminology'],

        // Generic tools and missing automotive system branches found inside the broad auto import.
        ['slug' => 'capete-tubulare-impact', 'from' => ['scule-speciale-auto'], 'all' => ['голов'], 'any' => ['ударн'], 'score' => 390, 'evidence' => 'impact socket inside broad automotive import'],
        ['slug' => 'tubulare-si-clichete', 'from' => ['scule-speciale-auto'], 'all' => ['голов'], 'any' => ['торцев'], 'none' => ['ударн'], 'score' => 340, 'evidence' => 'standard socket inside broad automotive import'],
        ['slug' => 'chei-si-surubelnite', 'from' => ['scule-speciale-auto'], 'any' => ['ключей комбинирован', 'ключей рожков', 'ключей накидн', 'ключ комбинирован', 'ключ рожков', 'ключ накидн'], 'score' => 330, 'evidence' => 'generic hand wrench inside broad automotive import'],
        ['slug' => 'biti-insertii-adaptoare', 'from' => ['scule-speciale-auto'], 'any' => ['вставок (бит)', 'вставка (бит)', 'держатель бит', 'переходник для бит'], 'score' => 330, 'evidence' => 'generic bit inside broad automotive import'],
        ['slug' => 'surubelnite-si-biti', 'from' => ['scule-speciale-auto'], 'any' => ['отвертк', 'отвёртк'], 'score' => 300, 'evidence' => 'generic screwdriver inside broad automotive import'],
        ['slug' => 'clesti-si-instrumente-taiere', 'from' => ['scule-speciale-auto'], 'any' => ['плоскогуб', 'пассатиж', 'бокорез', 'тонкогуб', 'кусач'], 'score' => 310, 'evidence' => 'generic pliers inside broad automotive import'],
        ['slug' => 'instrumente-izolate-vde', 'from' => ['scule-speciale-auto'], 'any' => ['диэлектр', 'vde', 'изолированных инструмент'], 'score' => 370, 'evidence' => 'VDE tool inside broad automotive import'],
        ['slug' => 'tinichigerie-si-richtuire', 'from' => ['scule-speciale-auto'], 'any' => ['стекол', 'облицовк', 'клипс', 'рихтов', 'кузов', 'уплотнител стек', 'вмятин', 'присоск'], 'score' => 360, 'evidence' => 'body, trim or glazing terminology'],
        ['slug' => 'scule-transmisie-ambreiaj', 'from' => ['scule-speciale-auto'], 'any' => ['сцеплен', 'кпп', 'акпп', 'трансмисс', 'коробк передач'], 'score' => 380, 'evidence' => 'transmission or clutch terminology'],
        ['slug' => 'scule-aer-conditionat-auto', 'from' => ['scule-speciale-auto'], 'any' => ['кондиционер', 'хладагент'], 'score' => 380, 'evidence' => 'automotive air-conditioning terminology'],
        ['slug' => 'scule-sistem-racire-auto', 'from' => ['scule-speciale-auto'], 'any' => ['системы охлаждения', 'патрубка охлаждения', 'хомутов радиатора'], 'score' => 385, 'evidence' => 'automotive cooling-system terminology'],
        ['slug' => 'sublere-micrometre-comparatoare', 'from' => ['scule-speciale-auto'], 'any' => ['нутромер', 'штангенцирк', 'микрометр'], 'none' => ['без микрометра'], 'score' => 360, 'evidence' => 'precision measuring tool inside broad automotive import'],
        ['slug' => 'goniometre', 'from' => ['scule-speciale-auto'], 'any' => ['угломер', 'шкала доворот'], 'score' => 360, 'evidence' => 'angle gauge inside broad automotive import'],
        ['slug' => 'consumabile-pentru-scule-pneumatice', 'from' => ['scule-speciale-auto'], 'any' => ['зубило для пневмомолотка'], 'score' => 370, 'evidence' => 'pneumatic hammer consumable inside broad automotive import'],
        ['slug' => 'clichete-pneumatice', 'from' => ['scule-speciale-auto'], 'any' => ['трещотка пневмат'], 'score' => 370, 'evidence' => 'pneumatic ratchet inside broad automotive import'],
        ['slug' => 'pistoale-pentru-silicon-si-gresare', 'from' => ['scule-speciale-auto'], 'all' => ['шприц'], 'any' => ['пневмат'], 'score' => 370, 'evidence' => 'pneumatic grease gun inside broad automotive import'],
        ['slug' => 'tubulare-si-clichete', 'from' => ['scule-speciale-auto'], 'any' => ['трещотка'], 'none' => ['пневмат'], 'score' => 350, 'evidence' => 'manual ratchet inside broad automotive import'],
        ['slug' => 'taiere-pilire-prelucrare', 'from' => ['scule-speciale-auto'], 'any' => ['набор зубил', 'набор просечек', 'скребок', 'монтировка'], 'none' => ['рихтов'], 'score' => 330, 'evidence' => 'generic manual cutting tool inside broad automotive import'],
        ['slug' => 'ciocane-si-unelte-lovire', 'from' => ['scule-speciale-auto'], 'any' => ['кувалд', 'молоток'], 'none' => ['рихтов', 'пневмат', 'обратн'], 'score' => 340, 'evidence' => 'generic striking tool inside broad automotive import'],

        // Remaining generic manual imports.
        ['slug' => 'instrumente-izolate-vde', 'from' => ['instrument-manual'], 'any' => ['диэлектр', 'vde', 'изолированных инструмент'], 'score' => 430, 'evidence' => 'VDE tool inside manual parent'],
        ['slug' => 'menghine-si-cleme', 'from' => ['instrument-manual'], 'any' => ['тиски', 'зажим слесар', 'струбцин'], 'score' => 380, 'evidence' => 'vice or clamp terminology'],
        ['slug' => 'ciocane-si-unelte-lovire', 'from' => ['instrument-manual'], 'any' => ['молоток', 'кувалд', 'киянк'], 'none' => ['пневмат', 'рихтов'], 'score' => 370, 'evidence' => 'manual striking tool terminology'],
        ['slug' => 'nituitoare-manuale', 'from' => ['instrument-manual'], 'any' => ['заклепочный пистолет', 'заклёпочный пистолет', 'заклепочник', 'заклёпочник'], 'none' => ['пневмат'], 'score' => 370, 'evidence' => 'manual riveter terminology'],
        ['slug' => 'carucioare-de-scule', 'from' => ['instrument-manual'], 'any' => ['тележка с инструментом', 'инструментальная тележка'], 'score' => 410, 'evidence' => 'tool trolley inside manual parent'],
        ['slug' => 'carucioare-pentru-rafturi', 'from' => ['instrument-manual'], 'any' => ['тележка передвижная полочная', 'тележка с полками', 'тележка диагностическая'], 'score' => 400, 'evidence' => 'shelf trolley inside manual parent'],
        ['slug' => 'sisteme-de-depozitare-si-transport', 'from' => ['instrument-manual'], 'any' => ['ящик для инструментов', 'органайзер с переставными'], 'score' => 380, 'evidence' => 'tool storage inside manual parent'],
        ['slug' => 'burghie-freze', 'from' => ['instrument-manual'], 'any' => ['сверло', 'набор фрез', 'фреза '], 'score' => 370, 'evidence' => 'drill or milling bit terminology'],
        ['slug' => 'taiere-pilire-prelucrare', 'from' => ['instrument-manual'], 'any' => ['скребок', 'ножницы', 'болторез', 'труборез'], 'score' => 360, 'evidence' => 'manual cutting tool terminology'],
        ['slug' => 'seringi-si-palnii', 'from' => ['instrument-manual'], 'any' => ['шприц для раздачи', 'воронка'], 'score' => 350, 'evidence' => 'fluid syringe or funnel terminology'],
        ['slug' => 'tinichigerie-si-richtuire', 'from' => ['instrument-manual'], 'any' => ['рихтов', 'автомобильных клипс'], 'score' => 360, 'evidence' => 'body repair terminology inside manual parent'],

        // Evacuate the last unrelated products from the electromontage parent.
        ['slug' => 'instrumente-izolate-vde', 'from' => ['instrumente-electromontaj'], 'any' => ['диэлектр', 'изолирован', 'vde'], 'score' => 500, 'evidence' => 'strong insulated VDE signal'],
        ['slug' => 'chei-si-surubelnite', 'from' => ['instrumente-electromontaj'], 'any' => ['ключей накидн', 'ключей рожков', 'ключ трубн', 'ключ газов'], 'none' => ['диэлектр', 'изолирован', 'vde'], 'score' => 380, 'evidence' => 'generic wrench inside electromontage parent'],
        ['slug' => 'menghine-si-cleme', 'from' => ['instrumente-electromontaj'], 'any' => ['зажим с фиксатор', 'зажим с прям', 'зажим с-образ', 'зажим с с-образ'], 'none' => ['диэлектр', 'изолирован', 'vde'], 'score' => 380, 'evidence' => 'generic clamp inside electromontage parent'],
        ['slug' => 'clesti-si-instrumente-taiere', 'from' => ['instrumente-electromontaj'], 'any' => ['шарнирно-губцев', 'захват переставн'], 'none' => ['диэлектр', 'изолирован', 'vde'], 'score' => 390, 'evidence' => 'generic adjustable pliers inside electromontage parent'],
        ['slug' => 'clesti-si-instrumente-taiere', 'from' => ['instrumente-electromontaj'], 'any' => ['болторез'], 'score' => 370, 'evidence' => 'bolt cutter inside electromontage parent'],
        ['slug' => 'cutite-lame-rezerve', 'from' => ['instrumente-electromontaj'], 'any' => ['нож со сменными лезвиями'], 'score' => 370, 'evidence' => 'utility knife inside electromontage parent'],
        ['slug' => 'scule-aer-conditionat-auto', 'from' => ['instrumente-electromontaj'], 'any' => ['системе кондиционирования', 'автокондиционер'], 'score' => 390, 'evidence' => 'automotive air-conditioning tool in wrong parent'],

        // Equipment incorrectly imported as generic hand tools.
        ['slug' => 'cricuri-hidraulice', 'from' => ['instrument-manual'], 'any' => ['домкрат'], 'score' => 330, 'evidence' => 'jack terminology'],
        ['slug' => 'capre-auto-si-suporturi', 'from' => ['instrument-manual'], 'any' => ['стойки автомобильные', 'подставка под автомобиль'], 'score' => 330, 'evidence' => 'vehicle support terminology'],
        ['slug' => 'multimetre-testere', 'from' => ['instrument-manual'], 'any' => ['токоизмеритель', 'мультиметр'], 'score' => 300, 'evidence' => 'electrical meter terminology'],

        // Generic hand-tool parent cleanup. Specific product types outrank generic set wording.
        ['slug' => 'capete-tubulare-impact', 'from' => ['instrument-manual'], 'all' => ['голов'], 'any' => ['ударн'], 'score' => 310, 'evidence' => 'impact socket terminology'],
        ['slug' => 'tubulare-si-clichete', 'from' => ['instrument-manual'], 'any' => ['торцевых головок', 'головок торцевых', 'трещотк', 'вороток'], 'score' => 260, 'evidence' => 'socket and ratchet terminology'],
        ['slug' => 'biti-insertii-adaptoare', 'from' => ['instrument-manual'], 'any' => ['вставка (бит)', 'набор вставок', 'набор в ложементе биты', 'набор в ложементе- биты', 'держатель бит', 'переходник для торцевых головок', 'переходник для бит', 'наконечник для рукоятки отв'], 'score' => 275, 'evidence' => 'bit or drive-adapter terminology'],
        ['slug' => 'surubelnite-si-biti', 'from' => ['instrument-manual'], 'any' => ['отверт', 'отвёрт'], 'score' => 260, 'evidence' => 'screwdriver terminology'],
        ['slug' => 'chei-dinamometrice', 'from' => ['instrument-manual'], 'any' => ['динамометр'], 'score' => 310, 'evidence' => 'torque-wrench terminology'],
        ['slug' => 'chei-si-surubelnite', 'from' => ['instrument-manual'], 'any' => ['ключ комбинирован', 'ключи комбинирован', 'ключ рожков', 'ключи рожков', 'ключ накидн', 'ключи накидн', 'ключ разрезн', 'ключи разрезн', 'l-образный ключ', 'набор ключей'], 'score' => 260, 'evidence' => 'hand-wrench terminology'],
        ['slug' => 'clesti-si-instrumente-taiere', 'from' => ['instrument-manual'], 'any' => ['пассатиж', 'плоскогуб', 'бокорез', 'кусач', 'щипц', 'клещи'], 'score' => 260, 'evidence' => 'pliers terminology'],
        ['slug' => 'tarozi-filiere-filetare', 'from' => ['instrument-manual'], 'any' => ['метчик', 'плашк', 'резьбонарез', 'восстановлени резьб'], 'score' => 285, 'evidence' => 'threading terminology'],
        ['slug' => 'taiere-pilire-prelucrare', 'from' => ['instrument-manual'], 'any' => ['напильник', 'ножовк', 'зубил', 'выколот', 'кернер'], 'score' => 260, 'evidence' => 'manual cutting and filing terminology'],
        ['slug' => 'seturi-de-scule', 'from' => ['instrument-manual'], 'any' => ['набор инструмента', 'набор в ложементе'], 'score' => 165, 'evidence' => 'generic hand-tool set terminology'],

        // Electromontage parent: keep electrical tools in their branch and evacuate unrelated imports.
        ['slug' => 'clesti-electrician-si-cabluri', 'from' => ['instrumente-electromontaj'], 'any' => ['стриппер', 'кримпер', 'кабелерез', 'обжим', 'зачистк', 'кабел', 'провод'], 'score' => 340, 'evidence' => 'electrician pliers or cable-tool terminology'],
        ['slug' => 'testere-electrice-si-indicatoare', 'from' => ['instrumente-electromontaj'], 'any' => ['напряжени', 'индикатор фаз', 'электрический тестер'], 'score' => 330, 'evidence' => 'electrical tester terminology'],
        ['slug' => 'lipire-si-consumabile', 'from' => ['instrumente-electromontaj'], 'any' => ['паяльник', 'припой', 'паяльная'], 'score' => 330, 'evidence' => 'soldering terminology'],
        ['slug' => 'instrumente-izolate-vde', 'from' => ['instrumente-electromontaj'], 'any' => ['диэлектр', 'изолирован', '1000v', '1000 v', 'vde'], 'score' => 250, 'evidence' => 'insulated VDE tool terminology'],
        ['slug' => 'surubelnite-si-biti', 'from' => ['instrumente-electromontaj'], 'any' => ['отверт', 'отвёрт'], 'none' => ['диэлектр', 'изолирован', '1000v', '1000 v', 'vde'], 'score' => 270, 'evidence' => 'non-electrical screwdriver in electromontage parent'],
        ['slug' => 'chei-si-surubelnite', 'from' => ['instrumente-electromontaj'], 'any' => ['ключ комбинирован', 'ключ рожков', 'ключ накидн', 'ключ разрезн', 'набор ключей'], 'none' => ['диэлектр', 'изолирован', '1000v', '1000 v', 'vde'], 'score' => 270, 'evidence' => 'non-electrical wrench in electromontage parent'],
        ['slug' => 'clesti-si-instrumente-taiere', 'from' => ['instrumente-electromontaj'], 'any' => ['пассатиж', 'плоскогуб', 'бокорез', 'кусач', 'щипц', 'клещи'], 'none' => ['диэлектр', 'изолирован', '1000v', '1000 v', 'vde', 'кабел', 'зачист', 'обжим', 'кримп', 'стриппер'], 'score' => 270, 'evidence' => 'non-electrical pliers in electromontage parent'],
    ],
];
