<?php

return [
    'enabled' => env('PRODUCT_PARSER_ENABLED', true),
    'max_sku_per_batch' => (int) env('PRODUCT_PARSER_MAX_SKU_PER_BATCH', 3000),
    'max_file_size_kb' => (int) env('PRODUCT_PARSER_MAX_FILE_SIZE_KB', 20480),
    'allowed_formats' => ['xls', 'xlsx', 'csv'],
    'max_images_per_product' => (int) env('PRODUCT_PARSER_MAX_IMAGES_PER_PRODUCT', 4),
    'min_confidence_score' => (int) env('PRODUCT_PARSER_MIN_CONFIDENCE_SCORE', 70),
    'image_size' => (int) env('PRODUCT_PARSER_IMAGE_SIZE', 1200),
    'preview_size' => (int) env('PRODUCT_PARSER_PREVIEW_SIZE', 600),
    'thumb_size' => (int) env('PRODUCT_PARSER_THUMB_SIZE', 300),
    'webp_quality' => (int) env('PRODUCT_PARSER_WEBP_QUALITY', 88),
    'search_images' => env('PRODUCT_PARSER_SEARCH_IMAGES', true),
    'translate_descriptions' => env('PRODUCT_PARSER_TRANSLATE_DESCRIPTIONS', true),
    'create_drafts_automatically' => env('PRODUCT_PARSER_CREATE_DRAFTS_AUTOMATICALLY', true),
    'update_existing_prices' => env('PRODUCT_PARSER_UPDATE_EXISTING_PRICES', false),
    'update_existing_stock' => env('PRODUCT_PARSER_UPDATE_EXISTING_STOCK', false),
    'add_photos_to_existing' => env('PRODUCT_PARSER_ADD_PHOTOS_TO_EXISTING', true),
    'replace_existing_photos' => env('PRODUCT_PARSER_REPLACE_EXISTING_PHOTOS', false),
    'allowed_domains' => [
        'tristool.md',
        'kingtony.com',
        'mighty-seven.com',
        'm7tools.com',
        'jtcautotools.com',
        'hoegert.com',
        'torin-usa.com',
    ],
    'blocked_domains' => [],
    'official_source_priority' => true,
    'watermark' => [
        'enabled' => env('PRODUCT_PARSER_WATERMARK_ENABLED', true),
        'file' => env('PRODUCT_PARSER_WATERMARK_FILE', '/images/brand/master-scule-logo.png'),
        'position' => env('PRODUCT_PARSER_WATERMARK_POSITION', 'bottom_right'),
        'opacity' => (int) env('PRODUCT_PARSER_WATERMARK_OPACITY', 14),
        'size_percent' => (int) env('PRODUCT_PARSER_WATERMARK_SIZE_PERCENT', 18),
    ],
    'category_rules' => [
        'min_confidence' => (int) env('PRODUCT_PARSER_MIN_CATEGORY_CONFIDENCE', 70),
        'group_mapping' => [
            'авторемонтный пневмоинструмент' => 'scule-pneumatice',
            'пневмоинструмент' => 'scule-pneumatice',
            'vde' => 'instrumente-electromontaj',
            'гидравлика' => 'cricuri-hidraulice',
            'гаражка' => 'echipamente-pentru-service',
            'tongrun' => 'echipamente-pentru-service',
            'torin big red' => 'echipamente-pentru-service',
            'hoegert' => 'instrument-manual',
            'jtc' => 'scule-speciale-auto',
            'benz & bmw' => 'scule-speciale-auto',
            'vw & audi' => 'scule-speciale-auto',
            'воротки' => 'tubulare-si-clichete',
            'трещотки' => 'tubulare-si-clichete',
            'переходы' => 'biti-insertii-adaptoare',
            'удлинители' => 'tubulare-si-clichete',
            'головки' => 'tubulare-si-clichete',
            'торцевые головки' => 'tubulare-si-clichete',
            'ударные головки' => 'capete-tubulare-impact',
            'шкафы и организация' => 'mobilier-pentru-service',
            'головки и трещотки' => 'tubulare-si-clichete',
            'ручной инструмент' => 'instrument-manual',
            'специнструмент автомобильный' => 'scule-speciale-auto',
        ],
        'sku_prefixes' => [
            'NC-' => 'chei-pneumatice',
            'QB-' => 'accesorii-pneumatice',
            'SG-' => 'furtunuri-cuple-accesorii',
            'SX-' => 'pistoale-suflat-si-sablare',
            'SB-' => 'pistoale-suflat-si-sablare',
            'TR' => 'echipamente-pentru-service',
            'JTC-' => 'scule-speciale-auto',
            'HT' => 'instrument-manual',
            '306' => 'surubelnite-si-biti',
            '*-MRVD' => 'instrumente-electromontaj',
        ],
        'keywords' => [
            'scule-pneumatice' => ['пневмо', 'пневматический', 'pneumatic', 'aer comprimat', 'гайковерт m7'],
            'instrumente-electromontaj' => ['vde', 'изолированный', 'диэлектрический', '1000v', 'electrician'],
            'seturi-de-scule' => ['набор инструментов', 'set', 'комплект', 'кейс', 'trusa'],
            'tubulare-si-clichete' => ['головка', 'трещотка', 'вороток', 'удлинитель', 'переходник', 'кардан', 'tubular', 'clichet', 'ratchet', 'socket'],
            'capete-tubulare-impact' => ['ударная головка', 'impact socket', 'crmo'],
            'chei-si-surubelnite' => ['ключ', 'рожковый', 'накидной', 'комбинированный', 'wrench', 'spanner'],
            'surubelnite-si-biti' => ['отвертка', 'отвёртка', 'screwdriver', 'surubelnita', 'bit', 'insert'],
            'chei-dinamometrice' => ['динамометрический', 'torque', 'dinamometric'],
            'extractoare-si-prese' => ['съемник', 'съёмник', 'puller', 'шаровая', 'подшипник', 'сайлентблок', 'extractor'],
            'scule-pentru-filtre-ulei' => ['масляный фильтр', 'oil filter', 'filtru ulei'],
            'scule-pentru-frane' => ['тормоз', 'brake', 'frane'],
            'scule-pentru-motor' => ['двигатель', 'engine', 'timing', 'camshaft', 'crankshaft', 'распредвал', 'коленвал'],
            'scule-pentru-suspensie' => ['подвеска', 'suspension', 'стойка', 'амортизатор'],
            'scule-speciale-auto' => ['benz', 'bmw', 'vw', 'audi', 'mercedes', 'opel', 'renault', 'jtc'],
            'compresoare' => ['компрессор', 'compresor'],
            'furtunuri-cuple-accesorii' => ['шланг', 'фитинг', 'муфта', 'quick coupler', 'racord', 'быстросъем', 'быстросьём'],
            'prese-hidraulice' => ['пресс', 'press', 'hydraulic press'],
            'cricuri-hidraulice' => ['домкрат', 'jack', 'hydraulic jack', 'подкатной'],
            'pompe-si-cilindri-hidraulici' => ['цилиндр', 'насос', 'cylinder', 'pump'],
            'macarale-standuri-suporti-motor' => ['кран', 'engine crane', 'stand', 'траверса', 'крепление мотора'],
            'echipamente-spalare-piese' => ['мойки деталей', 'мойка деталей', 'parts washer'],
            'masini-gaurit-insurubat' => ['дрель', 'шуруповерт', 'masina de gaurit'],
            'polizoare' => ['болгарка', 'шлифмашина', 'grinder', 'polizor'],
            'chei-cu-acumulator' => ['аккумуляторный гайковерт', 'cordless impact', 'impact acumulator'],
            'baterii-incarcatoare' => ['аккумулятор', 'battery', 'зарядное', 'charger', '20v', '18v', 'acumulator'],
            'sublere-micrometre-comparatoare' => ['штангенциркуль', 'микрометр', 'subler', 'micrometru'],
            'multimetre-testere' => ['мультиметр', 'tester'],
            'rulete-nivele' => ['рулетка', 'уровень', 'nivele'],
            'discuri-perii-abrazive' => ['диск', 'щетка', 'abrasive', 'perie'],
            'burghie-freze' => ['сверло', 'фреза', 'burghiu', 'freza'],
            'biti-si-capete' => ['бита', 'насадка', 'bit'],
            'cutite-lame-rezerve' => ['лезвие', 'нож', 'blade'],
            'accesorii-si-consumabile' => ['аксессуар', 'расходник', 'consumabil'],
            'mobilier-pentru-service' => ['тележка', 'шкаф', 'верстак', 'ящик', 'органайзер', 'carucior', 'dulap'],
            'echipament-protectie' => ['перчатки', 'очки', 'gloves', 'goggles', 'protectie'],
        ],
    ],
];
