<?php

return [
    'enabled' => env('PRODUCT_PARSER_ENABLED', true),
    'lock_store' => env('PRODUCT_PARSER_LOCK_STORE', 'file'),
    'max_sku_per_batch' => (int) env('PRODUCT_PARSER_MAX_SKU_PER_BATCH', 20000),
    'max_file_size_kb' => (int) env('PRODUCT_PARSER_MAX_FILE_SIZE_KB', 51200),
    'allowed_formats' => ['xls', 'xlsx', 'csv'],
    'max_images_per_product' => (int) env('PRODUCT_PARSER_MAX_IMAGES_PER_PRODUCT', 4),
    'min_confidence_score' => max(90, (int) env('PRODUCT_PARSER_MIN_CONFIDENCE_SCORE', 90)),
    'image_size' => (int) env('PRODUCT_PARSER_IMAGE_SIZE', 1200),
    'preview_size' => (int) env('PRODUCT_PARSER_PREVIEW_SIZE', 600),
    'thumb_size' => (int) env('PRODUCT_PARSER_THUMB_SIZE', 300),
    'webp_quality' => (int) env('PRODUCT_PARSER_WEBP_QUALITY', 84),
    'search_images' => env('PRODUCT_PARSER_SEARCH_IMAGES', true),
    'translate_descriptions' => env('PRODUCT_PARSER_TRANSLATE_DESCRIPTIONS', true),
    'automation_recovery_attempts' => (int) env('PRODUCT_PARSER_AUTOMATION_RECOVERY_ATTEMPTS', 3),
    'automation_recovery_delay_ms' => (int) env('PRODUCT_PARSER_AUTOMATION_RECOVERY_DELAY_MS', 250),
    'translation' => [
        'enabled' => env('PRODUCT_PARSER_TRANSLATE_DESCRIPTIONS', true),
        'base_url' => env('PRODUCT_PARSER_TRANSLATION_URL', 'https://translate.googleapis.com/translate_a/single'),
        'fallback_url' => env('PRODUCT_PARSER_TRANSLATION_FALLBACK_URL', 'https://api.mymemory.translated.net/get'),
        'timeout' => (int) env('PRODUCT_PARSER_TRANSLATION_TIMEOUT', 15),
    ],
    'create_drafts_automatically' => env('PRODUCT_PARSER_CREATE_DRAFTS_AUTOMATICALLY', true),
    'missing_stock_quantity' => max(1, (int) env('PRODUCT_PARSER_MISSING_STOCK_QUANTITY', 1)),
    'update_existing_prices' => env('PRODUCT_PARSER_UPDATE_EXISTING_PRICES', false),
    'update_existing_stock' => env('PRODUCT_PARSER_UPDATE_EXISTING_STOCK', false),
    'add_photos_to_existing' => env('PRODUCT_PARSER_ADD_PHOTOS_TO_EXISTING', true),
    'replace_existing_photos' => env('PRODUCT_PARSER_REPLACE_EXISTING_PHOTOS', false),
    'tristools' => [
        'enabled' => env('PARSER_TRISTOOLS_ENABLED', true),
        'base_url' => env('PARSER_TRISTOOLS_BASE_URL', 'https://tristool.md'),
        'timeout' => (int) env('PARSER_TRISTOOLS_TIMEOUT', 15),
        'rate_limit_ms' => (int) env('PARSER_TRISTOOLS_RATE_LIMIT_MS', 1000),
        'minimum_confidence' => 70,
    ],
    'allowed_domains' => [
        'kingtony.com',
        'mighty-seven.com',
        'jtc.com.tw',
        'jtcautotools.com',
        'hoegert.com',
        'torinjacks.com',
        'torin-usa.com',
        'tongrunjacks.com',
        'sklep.anb.com.pl',
    ],
    'blocked_domains' => env('PARSER_TRISTOOLS_ENABLED', true) ? [] : ['tristool.md'],
    'official_source_priority' => true,
    'official_sources_enabled' => env('PARSER_OFFICIAL_SOURCES_ENABLED', true),
    'tristools_fallback_enabled' => env('PARSER_TRISTOOLS_FALLBACK_ENABLED', true),
    'tristools_image_first' => true,
    'tristools_content_first' => true,
    'tristools_fallback_only' => false,
    'allow_marketplace_sources' => false,
    'min_official_confidence' => (int) env('PARSER_MIN_OFFICIAL_CONFIDENCE', 90),
    'min_fallback_confidence' => (int) env('PARSER_MIN_FALLBACK_CONFIDENCE', 80),
    'required_images_for_ready' => (int) env('PARSER_REQUIRED_IMAGES_FOR_READY', 1),
    'auto_approve_exact_fallback' => env('PARSER_AUTO_APPROVE_EXACT_FALLBACK', false),
    'reviewed_catalogs' => [
        [
            'brand_keys' => ['m7', 'mighty seven'],
            'source_name' => 'M7 2025/2026 reviewed manufacturer catalog',
            'source_url' => 'https://sklep.anb.com.pl/data/include/cms/M7/2025/Katalogi/2025_2026_Katalog_M7_int2.pdf',
            'directory' => 'images/parser-catalog/m7',
            'confidence' => 95,
            'assets' => [
                'db-1850' => 'db-1850.png',
                'dc-18a' => 'dc-18a.png',
                'dhg-101a' => 'dhg-101a.png',
                'drh-101a' => 'drh-101a.png',
                'nc-4650kit' => 'nc-4650kit.png',
                'qa-611a' => 'qa-611a.png',
                'qb-59642p39' => 'qb-59642p39.png',
                'qb-9211a' => 'qb-9211a.png',
                'qb-9213a' => 'qb-9213a.png',
                'qb-9323f' => 'qb-9323f.png',
                'qb-9433w' => 'qb-9433w.png',
                'qb-9434w' => 'qb-9434w.png',
                'qd-221t49' => 'qd-221t49.png',
                'qd-230t36' => 'qd-230t36.png',
                'qd-924' => 'qd-924.png',
                'qd-932' => 'qd-932.png',
                'qe-3a' => 'qe-3a.png',
                'qe-3b' => 'qe-3b.png',
                'qe-833p02' => 'qe-833p02.png',
                'qp-123p31' => 'qp-123p31.png',
                'ra-505an02' => 'ra-505an02.png',
                'sc-331-kit' => 'sc-331-kit.png',
                'sc-415' => 'sc-415.png',
                'sc-9337r' => 'sc-9337r.png',
            ],
        ],
    ],
    'source_registry' => [
        ['brands' => ['KING_TONY'], 'source_name' => 'King Tony official', 'domain' => 'kingtony.com', 'source_type' => 'official_manufacturer', 'auth_level' => 'public', 'priority' => 100, 'enabled' => true, 'rate_limit_per_minute' => 60],
        ['brands' => ['M7'], 'source_name' => 'Mighty Seven official', 'domain' => 'mighty-seven.com', 'source_type' => 'official_manufacturer', 'auth_level' => 'public', 'priority' => 100, 'enabled' => true, 'rate_limit_per_minute' => 60],
        ['brands' => ['JTC'], 'source_name' => 'JTC Taiwan official', 'domain' => 'jtc.com.tw', 'source_type' => 'official_manufacturer', 'auth_level' => 'public', 'priority' => 100, 'enabled' => true, 'rate_limit_per_minute' => 40],
        ['brands' => ['JTC'], 'source_name' => 'JTC Auto Tools official', 'domain' => 'jtcautotools.com', 'source_type' => 'official_manufacturer', 'auth_level' => 'public', 'priority' => 100, 'enabled' => true, 'rate_limit_per_minute' => 40],
        ['brands' => ['HOEGERT'], 'source_name' => 'Hoegert official', 'domain' => 'hoegert.com', 'source_type' => 'official_manufacturer', 'auth_level' => 'public', 'priority' => 100, 'enabled' => true, 'rate_limit_per_minute' => 40],
        ['brands' => ['TORIN'], 'source_name' => 'Torin Jacks official', 'domain' => 'torinjacks.com', 'source_type' => 'official_manufacturer', 'auth_level' => 'public', 'priority' => 100, 'enabled' => true, 'rate_limit_per_minute' => 40],
        ['brands' => ['TORIN'], 'source_name' => 'Torin USA official', 'domain' => 'torin-usa.com', 'source_type' => 'official_manufacturer', 'auth_level' => 'public', 'priority' => 100, 'enabled' => true, 'rate_limit_per_minute' => 40],
        ['brands' => ['TONGRUN'], 'source_name' => 'Tongrun official', 'domain' => 'tongrunjacks.com', 'source_type' => 'official_manufacturer', 'auth_level' => 'public', 'priority' => 100, 'enabled' => true, 'rate_limit_per_minute' => 40],
        ['brands' => ['M7'], 'source_name' => 'M7 reviewed manufacturer catalog', 'domain' => 'sklep.anb.com.pl', 'source_type' => 'official_manufacturer_catalog', 'auth_level' => 'public', 'priority' => 95, 'enabled' => true, 'rate_limit_per_minute' => 120],
        ['brands' => ['*'], 'source_name' => 'TrisTool primary', 'domain' => 'tristool.md', 'source_type' => 'tristools_primary', 'auth_level' => 'public', 'priority' => 120, 'enabled' => true, 'rate_limit_per_minute' => 30, 'fallback_only' => false],
    ],
    'watermark' => [
        'enabled' => env('PRODUCT_PARSER_WATERMARK_ENABLED', true),
        'file' => env('PRODUCT_PARSER_WATERMARK_FILE', '/images/brand/master-scule-logo.png'),
        'position' => env('PRODUCT_PARSER_WATERMARK_POSITION', 'bottom_right'),
        'opacity' => (int) env('PRODUCT_PARSER_WATERMARK_OPACITY', 14),
        'size_percent' => (int) env('PRODUCT_PARSER_WATERMARK_SIZE_PERCENT', 18),
    ],
    'category_rules' => [
        'min_confidence' => max(90, (int) env('PRODUCT_PARSER_MIN_CATEGORY_CONFIDENCE', 90)),
        'group_mapping' => [
            'авторемонтный пневмоинструмент' => 'scule-pneumatice',
            'пневмоинструмент' => 'scule-pneumatice',
            'аккумуляторный инструмент' => 'instrumente-cu-acumulator',
            'ручной инструмент' => 'instrument-manual',
            'специнструмент автомобильный' => 'scule-speciale-auto',
            'электромонтажный инструмент' => 'instrumente-electromontaj',
            'измерительный инструмент' => 'instrumente-de-masurare',
            'оснастка и расходники' => 'accesorii-si-consumabile',
            'шкафы и организация' => 'mobilier-pentru-service',
            'гаражка' => 'echipamente-pentru-service',
            'гидравлика' => 'echipamente-pentru-service',
            'vde' => 'instrumente-electromontaj',
            'jtc' => 'scule-speciale-auto',
            'hoegert' => 'instrument-manual',
            'tongrun' => 'echipamente-pentru-service',
            'torin big red' => 'echipamente-pentru-service',
            'головки' => 'tubulare-si-clichete',
            'трещотки' => 'tubulare-si-clichete',
            'ударные головки' => 'capete-tubulare-impact',
        ],
        'sku_prefixes' => [
            'NC-' => 'chei-pneumatice',
            'QB-' => 'accesorii-pneumatice',
            'SG-' => 'furtunuri-cuple-accesorii',
            'SX-' => 'pistoale-suflat-si-sablare',
            'SB-' => 'pistoale-suflat-si-sablare',
            'DW-' => 'instrumente-cu-acumulator',
            'DS-' => 'instrumente-cu-acumulator',
            'TR' => 'echipamente-pentru-service',
            'JTC-' => 'scule-speciale-auto',
            'HT' => 'instrument-manual',
            '306' => 'instrumente-electromontaj',
            '*-MRVD' => 'instrumente-electromontaj',
        ],
        'keywords' => [
            'scule-pneumatice' => ['пневмо', 'пневматический', 'pneumatic', 'air tool', 'aer comprimat'],
            'chei-pneumatice' => ['пневмогайковерт', 'гайковерт пневматический', 'air impact wrench'],
            'instrumente-cu-acumulator' => ['аккумуляторный', 'аккумулятор', 'cordless', 'battery', '18v', '20v'],
            'instrumente-electromontaj' => ['vde', 'изолированный', 'диэлектрический', '1000v', 'электрик', 'кабель', 'обжим'],
            'seturi-de-scule' => ['набор инструментов', 'комплект инструментов', 'tool set', 'trusa', 'кейс'],
            'tubulare-si-clichete' => ['головка', 'трещотка', 'вороток', 'удлинитель', 'кардан', 'socket', 'ratchet'],
            'capete-tubulare-impact' => ['ударная головка', 'impact socket', 'cr-mo', 'crmo'],
            'chei-si-surubelnite' => ['ключ', 'рожковый', 'накидной', 'комбинированный', 'wrench', 'spanner'],
            'surubelnite-si-biti' => ['отвертка', 'отвёртка', 'screwdriver', 'surubelnita', 'бита'],
            'chei-dinamometrice' => ['динамометрический', 'torque', 'dinamometric'],
            'extractoare-si-prese' => ['съемник', 'съёмник', 'puller', 'подшипник', 'сайлентблок'],
            'scule-pentru-frane' => ['тормоз', 'brake', 'frane'],
            'scule-pentru-motor' => ['двигатель', 'грм', 'распредвал', 'коленвал', 'engine', 'timing'],
            'scule-pentru-suspensie' => ['подвеска', 'амортизатор', 'пружина', 'suspension'],
            'scule-speciale-auto' => ['bmw', 'mercedes', 'audi', 'volkswagen', 'vw', 'opel', 'renault', 'jtc'],
            'compresoare' => ['компрессор', 'compressor', 'compresor'],
            'furtunuri-cuple-accesorii' => ['шланг', 'фитинг', 'муфта', 'быстросъем', 'быстросъём', 'hose', 'coupler'],
            'prese-hidraulice' => ['гидравлический пресс', 'hydraulic press'],
            'cricuri-hidraulice' => ['домкрат', 'hydraulic jack', 'cric'],
            'pompe-si-cilindri-hidraulici' => ['гидравлический насос', 'гидравлический цилиндр', 'hydraulic pump', 'hydraulic cylinder'],
            'macarale-standuri-suporti-motor' => ['кран для двигателя', 'стойка двигателя', 'engine crane', 'engine stand'],
            'echipamente-spalare-piese' => ['мойка деталей', 'parts washer'],
            'electroinstrumente' => ['электроинструмент', 'электрическая дрель', 'болгарка', 'corded tool'],
            'masini-gaurit-insurubat' => ['дрель', 'шуруповерт', 'шуруповёрт', 'drill'],
            'polizoare' => ['болгарка', 'шлифмашина', 'grinder', 'polizor'],
            'sublere-micrometre-comparatoare' => ['штангенциркуль', 'микрометр', 'индикатор', 'caliper', 'micrometer'],
            'multimetre-testere' => ['мультиметр', 'тестер', 'multimeter'],
            'rulete-nivele' => ['рулетка', 'уровень', 'laser', 'ruleta'],
            'discuri-perii-abrazive' => ['абразивный диск', 'щетка', 'щётка', 'abrasive disc', 'perie'],
            'burghie-freze' => ['сверло', 'фреза', 'burghiu', 'freza'],
            'biti-si-capete' => ['бита', 'насадка', 'bit set'],
            'cutite-lame-rezerve' => ['лезвие', 'нож', 'blade'],
            'accesorii-si-consumabile' => ['расходник', 'аксессуар', 'consumable', 'accessory'],
            'mobilier-pentru-service' => ['тележка для инструментов', 'инструментальный шкаф', 'верстак', 'органайзер', 'tool cabinet', 'tool trolley'],
            'echipament-protectie' => ['перчатки', 'защитные очки', 'gloves', 'goggles'],
        ],
    ],
];
