<?php

return [
    'enabled' => env('PRODUCT_PARSER_ENABLED', true),
    'max_sku_per_batch' => (int) env('PRODUCT_PARSER_MAX_SKU_PER_BATCH', 6000),
    'max_file_size_kb' => (int) env('PRODUCT_PARSER_MAX_FILE_SIZE_KB', 20480),
    'allowed_formats' => ['xls', 'xlsx', 'csv'],
    'max_images_per_product' => (int) env('PRODUCT_PARSER_MAX_IMAGES_PER_PRODUCT', 4),
    'min_confidence_score' => (int) env('PRODUCT_PARSER_MIN_CONFIDENCE_SCORE', 70),
    'image_size' => (int) env('PRODUCT_PARSER_IMAGE_SIZE', 1000),
    'preview_size' => (int) env('PRODUCT_PARSER_PREVIEW_SIZE', 500),
    'thumb_size' => (int) env('PRODUCT_PARSER_THUMB_SIZE', 320),
    'webp_quality' => (int) env('PRODUCT_PARSER_WEBP_QUALITY', 84),
    'search_images' => env('PRODUCT_PARSER_SEARCH_IMAGES', true),
    'translate_descriptions' => env('PRODUCT_PARSER_TRANSLATE_DESCRIPTIONS', true),
    'create_drafts_automatically' => env('PRODUCT_PARSER_CREATE_DRAFTS_AUTOMATICALLY', true),
    'update_existing_prices' => env('PRODUCT_PARSER_UPDATE_EXISTING_PRICES', false),
    'update_existing_stock' => env('PRODUCT_PARSER_UPDATE_EXISTING_STOCK', false),
    'add_photos_to_existing' => env('PRODUCT_PARSER_ADD_PHOTOS_TO_EXISTING', true),
    'replace_existing_photos' => env('PRODUCT_PARSER_REPLACE_EXISTING_PHOTOS', false),
    'allowed_domains' => [
        'kingtony.com',
        'mighty-seven.com',
        'jtc.com.tw',
        'jtcautotools.com',
        'hoegert.com',
        'torinjacks.com',
        'torin-usa.com',
        'tongrunjacks.com',
    ],
    'blocked_domains' => ['tristool.md'],
    'official_source_priority' => true,
    'watermark' => [
        'enabled' => env('PRODUCT_PARSER_WATERMARK_ENABLED', false),
        'file' => env('PRODUCT_PARSER_WATERMARK_FILE', '/images/brand/master-scule-logo.png'),
        'position' => env('PRODUCT_PARSER_WATERMARK_POSITION', 'bottom_right'),
        'opacity' => (int) env('PRODUCT_PARSER_WATERMARK_OPACITY', 14),
        'size_percent' => (int) env('PRODUCT_PARSER_WATERMARK_SIZE_PERCENT', 18),
    ],
    'category_rules' => [
        'min_confidence' => (int) env('PRODUCT_PARSER_MIN_CATEGORY_CONFIDENCE', 70),
        'group_mapping' => [
            'авторемонтный пневмоинструмент' => 'scule-pneumatice',
            'пневмоинструмент' => 'scule-pneumatice',
            'аккумуляторный инструмент' => 'instrumente-cu-acumulator',
            'ручной инструмент' => 'instrument-manual',
            'специнструмент автомобильный' => 'scule-speciale-auto',
            'электромонтажный инструмент' => 'instrumente-electromontaj',
            'измерительный инструмент' => 'instrumente-de-masurare',
            'оснастка и расходники' => 'accesorii-si-consumabile',
            'шкафы и организация' => 'mobilier-pentru-service',
            'гаражка' => 'echipamente-pentru-service',
            'гидравлика' => 'echipamente-pentru-service',
            'vde' => 'instrumente-electromontaj',
            'jtc' => 'scule-speciale-auto',
            'hoegert' => 'instrument-manual',
            'tongrun' => 'echipamente-pentru-service',
            'torin big red' => 'echipamente-pentru-service',
            'головки' => 'tubulare-si-clichete',
            'трещотки' => 'tubulare-si-clichete',
            'ударные головки' => 'capete-tubulare-impact',
        ],
        'sku_prefixes' => [
            'NC-' => 'chei-pneumatice',
            'QB-' => 'accesorii-pneumatice',
            'SG-' => 'furtunuri-cuple-accesorii',
            'SX-' => 'pistoale-suflat-si-sablare',
            'SB-' => 'pistoale-suflat-si-sablare',
            'DW-' => 'instrumente-cu-acumulator',
            'DS-' => 'instrumente-cu-acumulator',
            'TR' => 'echipamente-pentru-service',
            'JTC-' => 'scule-speciale-auto',
            'HT' => 'instrument-manual',
            '306' => 'instrumente-electromontaj',
            '*-MRVD' => 'instrumente-electromontaj',
        ],
        'keywords' => [
            'scule-pneumatice' => ['пневмо', 'пневматический', 'pneumatic', 'air tool', 'aer comprimat'],
            'chei-pneumatice' => ['пневмогайковерт', 'гайковерт пневматический', 'air impact wrench'],
            'instrumente-cu-acumulator' => ['аккумуляторный', 'аккумулятор', 'cordless', 'battery', '18v', '20v'],
            'instrumente-electromontaj' => ['vde', 'изолированный', 'диэлектрический', '1000v', 'электрик', 'кабель', 'обжим'],
            'seturi-de-scule' => ['набор инструментов', 'комплект инструментов', 'tool set', 'trusa', 'кейс'],
            'tubulare-si-clichete' => ['головка', 'трещотка', 'вороток', 'удлинитель', 'кардан', 'socket', 'ratchet'],
            'capete-tubulare-impact' => ['ударная головка', 'impact socket', 'cr-mo', 'crmo'],
            'chei-si-surubelnite' => ['ключ', 'рожковый', 'накидной', 'комбинированный', 'wrench', 'spanner'],
            'surubelnite-si-biti' => ['отвертка', 'отвёртка', 'screwdriver', 'surubelnita', 'бита'],
            'chei-dinamometrice' => ['динамометрический', 'torque', 'dinamometric'],
            'extractoare-si-prese' => ['съемник', 'съёмник', 'puller', 'подшипник', 'сайлентблок'],
            'scule-pentru-frane' => ['тормоз', 'brake', 'frane'],
            'scule-pentru-motor' => ['двигатель', 'грм', 'распредвал', 'коленвал', 'engine', 'timing'],
            'scule-pentru-suspensie' => ['подвеска', 'амортизатор', 'пружина', 'suspension'],
            'scule-speciale-auto' => ['bmw', 'mercedes', 'audi', 'volkswagen', 'vw', 'opel', 'renault', 'jtc'],
            'compresoare' => ['компрессор', 'compressor', 'compresor'],
            'furtunuri-cuple-accesorii' => ['шланг', 'фитинг', 'муфта', 'быстросъем', 'быстросъём', 'hose', 'coupler'],
            'prese-hidraulice' => ['гидравлический пресс', 'hydraulic press'],
            'cricuri-hidraulice' => ['домкрат', 'hydraulic jack', 'cric'],
            'pompe-si-cilindri-hidraulici' => ['гидравлический насос', 'гидравлический цилиндр', 'hydraulic pump', 'hydraulic cylinder'],
            'macarale-standuri-suporti-motor' => ['кран для двигателя', 'стойка двигателя', 'engine crane', 'engine stand'],
            'echipamente-spalare-piese' => ['мойка деталей', 'parts washer'],
            'electroinstrumente' => ['электроинструмент', 'электрическая дрель', 'болгарка', 'corded tool'],
            'masini-gaurit-insurubat' => ['дрель', 'шуруповерт', 'шуруповёрт', 'drill'],
            'polizoare' => ['болгарка', 'шлифмашина', 'grinder', 'polizor'],
            'sublere-micrometre-comparatoare' => ['штангенциркуль', 'микрометр', 'индикатор', 'caliper', 'micrometer'],
            'multimetre-testere' => ['мультиметр', 'тестер', 'multimeter'],
            'rulete-nivele' => ['рулетка', 'уровень', 'laser', 'ruleta'],
            'discuri-perii-abrazive' => ['абразивный диск', 'щетка', 'щётка', 'abrasive disc', 'perie'],
            'burghie-freze' => ['сверло', 'фреза', 'burghiu', 'freza'],
            'biti-si-capete' => ['бита', 'насадка', 'bit set'],
            'cutite-lame-rezerve' => ['лезвие', 'нож', 'blade'],
            'accesorii-si-consumabile' => ['расходник', 'аксессуар', 'consumable', 'accessory'],
            'mobilier-pentru-service' => ['тележка для инструментов', 'инструментальный шкаф', 'верстак', 'органайзер', 'tool cabinet', 'tool trolley'],
            'echipament-protectie' => ['перчатки', 'защитные очки', 'gloves', 'goggles'],
        ],
    ],
];
